'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import type { MorphMark } from './morph-shapes';

/**
 * A mark that turns into a different mark as you scroll past it.
 *
 * How it works, and why this way:
 *  - The CSS `d` property is animatable only in Blink, so a CSS-only morph would silently do
 *    nothing in Firefox and Safari. The interpolation is done in JS instead.
 *  - Both states are generated by `blob()` (morph-shapes.ts), so the two `d` strings always share
 *    one command skeleton — `M + 4×C + Z`. That makes a pairwise numeric lerp valid rather than
 *    garbage, and it cannot rot when someone edits one half of a pair.
 *  - The interpolated `t` lives in React state and the paths are computed during render. The first
 *    version wrote `d` straight to the DOM through refs to avoid re-rendering, and it silently did
 *    nothing: the JSX still declared `d={mark.outer.from}`, so React restored the starting shape on
 *    the very next re-render of the parent. Only this component re-renders here, and it is two
 *    paths, so React owning the value costs nothing and cannot be undone behind our back.
 *  - One module-level scroll listener and one rAF serve every morph on the page, the same shape as
 *    the sticker layer, so adding marks costs nothing per mark.
 *
 * Rules it respects: the shape is fully drawn at rest (never invisible waiting on JS or an
 * animation delay — that bug bit twice already), and under prefers-reduced-motion the morph simply
 * does not run, leaving the `from` state, which is a complete icon in its own right.
 *
 * CONTROLLED MODE (`progress`) is the one to reach for by default. Scroll-driving was the first
 * idea and it was wrong here: measured live, /student, /student/browse and /student/profile all
 * report a maximum scroll of 0 — they are shorter than the viewport — so a scroll-driven morph on
 * any of them could never advance past its first frame. Driving the transform from what the page
 * is ABOUT (a filter being chosen, a tab being opened, a real progress value) is both more robust
 * and more meaningful than driving it from page depth.
 */

type Sub = (y: number, h: number) => void;
const subs = new Set<Sub>();
let frame = 0;
let listening = false;

function tick() {
  if (frame) return;
  frame = requestAnimationFrame(() => {
    frame = 0;
    const y = window.scrollY;
    const h = window.innerHeight || 1;
    subs.forEach((fn) => fn(y, h));
  });
}

function subscribe(fn: Sub) {
  subs.add(fn);
  if (!listening) {
    window.addEventListener('scroll', tick, { passive: true });
    window.addEventListener('resize', tick, { passive: true });
    listening = true;
  }
  tick();
  return () => {
    subs.delete(fn);
    if (subs.size === 0 && listening) {
      window.removeEventListener('scroll', tick);
      window.removeEventListener('resize', tick);
      listening = false;
      if (frame) cancelAnimationFrame(frame);
      frame = 0;
    }
  };
}

/** Pull the numbers out of a path, leaving the command letters as the skeleton. */
const NUMS = /-?\d*\.?\d+/g;
function numbersOf(d: string): number[] {
  return (d.match(NUMS) ?? []).map(Number);
}
function skeletonOf(d: string): string {
  return d.replace(NUMS, '').replace(/\s+/g, ' ').trim();
}

/** Build an interpolator, or null when the two paths are not structurally compatible. */
function lerper(from: string, to: string): ((t: number) => string) | null {
  const a = numbersOf(from);
  const b = numbersOf(to);
  if (a.length !== b.length || skeletonOf(from) !== skeletonOf(to)) return null;
  const parts = from.split(NUMS);
  return (t: number) => {
    let out = '';
    for (let i = 0; i < a.length; i++) {
      out += parts[i] + (a[i] + (b[i] - a[i]) * t).toFixed(2);
    }
    return out + parts[a.length];
  };
}

const TONE: Record<string, string> = {
  signal: 'var(--signal)',
  mint: 'var(--mint)',
  warning: 'var(--warning)',
  ink: 'var(--ink-faint)',
};

export function ScrollMorph({
  mark,
  size = 44,
  tone = 'signal',
  opacity = 0.5,
  className,
  style,
  label,
  drive = 'element',
  range = 420,
  progress,
}: {
  mark: MorphMark;
  size?: number;
  tone?: keyof typeof TONE;
  opacity?: number;
  className?: string;
  style?: React.CSSProperties;
  /** Screen-reader description; omit to keep the mark decorative. */
  label?: string;
  /**
   * What advances the morph.
   *  'element' — the mark's own travel up the viewport. Right for a mark sitting mid-page.
   *  'page'    — absolute scroll depth over `range` px. Required for anything in a HEADER: a
   *              header already sits high on screen at rest, so element-driven progress would be
   *              pinned at 1 and the mark would render already-transformed, never showing its
   *              first state at all.
   */
  drive?: 'element' | 'page';
  /** Scroll distance in px that completes a 'page'-driven morph. */
  range?: number;
  /**
   * 0..1. When supplied the mark is CONTROLLED and scroll is ignored: the caller decides what the
   * transform means. Changes are tweened so the shape travels rather than snapping.
   */
  progress?: number;
}) {
  const hostRef = useRef<HTMLSpanElement>(null);
  const [t, setT] = useState(0);

  const lerpOuter = useMemo(() => lerper(mark.outer.from, mark.outer.to), [mark]);
  const lerpInner = useMemo(() => lerper(mark.inner.from, mark.inner.to), [mark]);
  // Structurally incompatible paths fall back to the first state, which is a complete icon.
  const dOuter = lerpOuter ? lerpOuter(t) : mark.outer.from;
  const dInner = lerpInner ? lerpInner(t) : mark.inner.from;

  // ---- controlled: the caller owns the value ----
  const currentRef = useRef(0);
  useEffect(() => {
    if (progress === undefined) return;
    const target = Math.max(0, Math.min(1, progress));
    const apply = (v: number) => {
      currentRef.current = v;
      setT(v);
    };

    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
      apply(target);
      return;
    }

    const start = currentRef.current;
    const t0 = performance.now();
    const dur = 420;
    let raf = 0;
    const step = (now: number) => {
      const k = Math.min((now - t0) / dur, 1);
      apply(start + (target - start) * (k * k * (3 - 2 * k)));
      if (k < 1) raf = requestAnimationFrame(step);
    };
    raf = requestAnimationFrame(step);
    // requestAnimationFrame does not run in a background tab, so land the final value regardless
    // rather than leaving the mark stranded mid-transform.
    const settle = setTimeout(() => apply(target), dur + 260);
    return () => {
      cancelAnimationFrame(raf);
      clearTimeout(settle);
    };
  }, [progress]);

  // ---- uncontrolled: driven by scroll ----
  useEffect(() => {
    if (progress !== undefined) return;
    const host = hostRef.current;
    if (!host) return;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

    let last = -1;
    return subscribe((y, vh) => {
      let raw: number;
      if (drive === 'page') {
        raw = y / Math.max(range, 1);
      } else {
        const rect = host.getBoundingClientRect();
        const centre = rect.top + rect.height / 2;
        // 1 when the mark reaches the top third, 0 while it is still low on screen. The transform
        // completes as it travels up the viewport, so the change is read as caused by scrolling.
        raw = 1 - (centre - vh * 0.28) / (vh * 0.62);
      }
      const t = Math.max(0, Math.min(1, raw));
      const eased = t * t * (3 - 2 * t); // smoothstep — no abrupt start or stop
      if (Math.abs(eased - last) < 0.004) return;
      last = eased;
      currentRef.current = eased;
      setT(eased);
    });
  }, [mark, drive, range, progress]);

  return (
    <span
      ref={hostRef}
      className={className}
      style={{ display: 'block', color: TONE[tone] ?? TONE.signal, opacity, ...style }}
      {...(label ? { role: 'img', 'aria-label': label } : { 'aria-hidden': true })}
    >
      <svg
        viewBox="0 0 32 32"
        width={size}
        height={size}
        fill="none"
        stroke="currentColor"
        strokeWidth={1.6}
        strokeLinecap="round"
        strokeLinejoin="round"
        focusable="false"
      >
        {/* t starts at 0, so the server and the first client render both emit the `from` state
            and hydration always matches. */}
        <path d={dOuter} />
        <path d={dInner} opacity={0.62} />
      </svg>
    </span>
  );
}
